### ISSUE TITLE
Role and Skills texts within the settings page need to be replaced.

### ISSUE THREAD

**Issue by gabriela99** [gabriela99/capstone-code#10]
Role and Skills default texts are problematic as the user might go to settings, not have anything to write in the skills section, and then will not be allowed to save unless they write a skill. This is due to the fact that Role and Skills are text placeholders but will not be accepted under the save conditions.

**Comment by ekhattar** [comment]
## Approach

So we want to handle values like `""` for input fields (or like in the issue, where you want to use `"role"`).

Let's think about what would happen if a user wants to have no roles or skills.

__Right now, this would fail the validation__ as you pointed out

In `SettingsActivity.java`, we need to make some small changes to first check if the input fields are empty.

Let's look at the validator function `validateInput()`.

We can use a special way of assigning variables that looks like `myvar = a || b`.

This means that if `a` can be evaluated, `myvar` will be assigned the value of `a`. Otherwise, it takes the value of `b`.

- [See the section on logical operators ||](https://www.w3schools.com/java/java_operators.asp)

We do exactly the same for validating `role` and `skills`.

**Note**: first `trim()` should be used to remove hanging whitespace, because we want `" "` to be the same as `""`

So what is going on in the below is that we check for both `isRoleValid` and `isSkillsValid` if what's left of the `||` can be evaluated, otherwise check if the input field is an empty string `""` to set the final value of `isXValid`.

This means if the first part returns `false` then we check the second part (which can be `true` or `false`) and assign its value to `isRoleValid`/`isSkillsValid`.

Otherwise, if the first part returns `true`, we assign that directly.

```java

    // Checks that user input conforms to the list of options: true if valid input, false if invalid
    private boolean validateInput() {
        // Retrieve what the user inputted into the fields
        role = mRole.getText().toString().trim();
        skills = mSkills.getText().toString().trim();
        // Do the check for both fields
        boolean isRoleValid = isStringInList(roleOptions, role) || role.equals("");
        // Check if the skills the user entered are all from the predefined list
        boolean isSkillsValid = isStringInList(skillOptions, skills) || skills.equals("");
        // If both role and skills are from the predefined list, return true for valid settings
        if (isRoleValid && isSkillsValid) {
            return true;
        } else {
            return false;
        }
    }
```

__Therefore, if you wanted for example to say that `"role"` is a valid input for the role field__, then just do `role.equals("role")`

### Side note

In `ProfileActivity.java`, when you retrieve data from the database, what would happen when the value is `null`?

You can't do `toString()` on `null` - the app will crash. This is probably why you for new users set the role as `"role"` and same for skills (hence this issue of this not being a valid input).

```java
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                // Fetch information from Firebase for the user with the data snapshot
                String mUserName = dataSnapshot.child("name").getValue().toString();
                String mRole = dataSnapshot.child("role").getValue().toString();
                String mSkills = dataSnapshot.child("skills").getValue().toString();
```

If you notice, in `SettingsActivity` you approached this a different way:

```java
    private void getUserInfo() {
        mCustomerDatabase.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if (dataSnapshot.exists() && dataSnapshot.getChildrenCount() > 0) {
                    Map<String, Object> map = (Map<String, Object>) dataSnapshot.getValue();
                    if (map.get("name") != null) {
                        name = map.get("name").toString();
                        mUserName.setText(name);
                    }
```

There, you retrieve the data __first__, then __check if not null__, then __turn to a string__. 

This is exactly what should be done also in `ProfileActivity`.

The crash can be fixed by modifying `ProfileActivity.java` to first retrieve the database objects.

Then, using a __ternary operator__ conditionally setting the value of `mUserName`, `mRole`, and `mSkills`

A ternary operator is a way to write if statements in one line in the form `condition ? value if true : value if not true`. 

- [About the ternary operator](https://www.baeldung.com/java-ternary-operator)
- [More about the ternary operator](https://howtodoinjava.com/java/basics/operators-in-java/#ternary)

In the below, the fallback (value if not true) is simply `""` for the three fields

```java

            public void onDataChange(DataSnapshot dataSnapshot) {
                Object dbUserName = dataSnapshot.child("name").getValue();
                Object dbRole = dataSnapshot.child("role").getValue();
                Object dbSkills = dataSnapshot.child("skills").getValue();

                String mUserName = dbUserName != null ? dbUserName.toString() : "";
                String mRole = dbRole != null ? dbRole.toString() : "";
                String mSkills = dbSkills != null ? dbSkills.toString() : "";
                ...
```

### Putting it all together

__What happened__

1. You set default role & skill values in https://github.com/gabriela99/capstone-code/commit/0c09dcff9bfba2397f63c7828cdec9c16db4f060 (where role is `Role` and skills would be `Skills`)
2. This makes problems for editing profile, because these are both not valid options for their respective fields

__How to approach this__

1. You don't need to set default role & skill values as long as everywhere you retrieve database values, you first check if they are `null`
     - one place this change needs to happen is in `ProfileActivity`
     - you should make sure to do this check __everywhere__ you interact with the db --> e.g., search results, other profiles, etc
     - another option: if you want to set default values instead of dealing with `null`, just set them to `""` empty strings because this won't raise problems with `toString()`
      - E.g., in `RegisterActivity`
```java
                        userInfo.put("role", ""); // empty string ok
                        userInfo.put("skills", ""); // empty string ok
                        currentUserDb.updateChildren(userInfo);
```
2. Empty values should be allowed for role & skills (so values like `""`) because this is a valid business requirement (what if users have no skills?)
3. You can allow these by using the `||` operator in the __validator__ function of `SettingsActivity` to check if the input is actually empty
4. If the fields are actually empty strings `""`, then just mark them as valid

## Bonus side note for name validation

Right now, the validator function in `SettingsActivity` only checks the values of role & skills.

However, it's also a must that each user sets their `name`

Therefore, you should extend the validator to also get the value of the name field & make sure it's __not__ empty (! `""`)

In validateInput function....
```java
        // get the name same as you do now when you want to save the data
        name = mUserName.getText().toString().trim();

        boolean isNameValid = name.length() >= 1;
        ....
        // If both role and skills are from the predefined list, return true for valid settings
        if (isRoleValid && isSkillsValid && isNameValid) {
            return true;
        } else {
            return false;
        }
```

**Comment by gabriela99** [comment]
I implemented the empty string conditions, checking for null, and the check to ensure the user has a name.
