### ISSUE TITLE
On profile page, logout button takes user to settings page and doesn't log user out

### ISSUE THREAD

**Issue by gabriela99** [gabriela99/capstone-code#6]
https://github.com/gabriela99/capstone-code/blob/7d2a884f0434efec0de74c5d67900ccc765330c7/app/src/main/java/com/example/capstone_code/ProfileActivity.java#L77

**Comment by ekhattar** [comment]
## Description

At the moment, logout doesn't work

In the changes from https://github.com/gabriela99/capstone-code/commit/33827999944f9ac8f8ede5e7db71017984b31c11#diff-af077caf9006718bc4f89192246cf0bd, the following line changed from:
```
FirebaseAuth.getInstance().signOut();
```
to:

https://github.com/gabriela99/capstone-code/blob/7d2a884f0434efec0de74c5d67900ccc765330c7/app/src/main/java/com/example/capstone_code/ProfileActivity.java#L79

If reverting to `FirebaseAuth.getInstance().signOut();` (instead of `mFirebaseAuth.signOut();`) logout will work again

It looks like although `mFirebaseAuth` is defined at the top as a variable of type `FirebaseAUth`

https://github.com/gabriela99/capstone-code/blob/7d2a884f0434efec0de74c5d67900ccc765330c7/app/src/main/java/com/example/capstone_code/ProfileActivity.java#L21-L25

it's never given a value that's accessible in the `logoutUser()` function, which is why trying to call ` mFirebaseAuth.signOut();` fails

Therefore, it would also work to first define `mFirebaseAuth`:
```
    public void logoutUser(View view) {
        // Sign user out
        mFirebaseAuth = FirebaseAuth.getInstance();
        mFirebaseAuth.signOut();
```

**Comment by gabriela99** [comment]
Added instatiation of the firebase auth.
